In [33]:
# Filename: array_example.py

import numpy as np

a = np.array([10, 20, 30])            # Create a rank 1 array
print(type(a))                        # Output: <class 'numpy.ndarray'>
print(a.shape)                        # Output: (3,)
print(a[0], a[1], a[2])               # Output: 10 20 30
a[0] = 50                             # Modify an element of the array
print(a)                              # Output: [50 20 30]
b = np.array([[7, 8, 9], [10, 11, 12]]) # Create a rank 2 array
print(b.shape)                        # Output: (2, 3)
print(b[0, 0], b[0, 1], b[1, 0])      # Same as b[0][0], b[0][1], b[1][0]. Output: 7 8 10

<class 'numpy.ndarray'>
(3,)
10 20 30
[50 20 30]
(2, 3)
7 8 10


In [72]:
# Filename: array_generation.py

import numpy as np

a = np.zeros((3,3))          # Generate an array filled with zeros
print(a)                     # Output: [[ 0.  0.  0.]
                             #          [ 0.  0.  0.]
                             #          [ 0.  0.  0.]]
b = np.ones((2,3))           # Generate an array filled with ones
print(b)                     # Output: [[ 1.  1.  1.]
                             #          [ 1.  1.  1.]]

c = np.full((3,2), 5)        # Generate an array with a constant value
print(c)                     # Output: [[ 5  5]
                             #          [ 5  5]
                             #          [ 5  5]]
d = np.eye(3)                # Generate a 3x3 identity matrix
print(d)                     # Output: [[ 1.  0.  0.]
                             #          [ 0.  1.  0.]
                             #          [ 0.  0.  1.]]
e = np.random.rand(3,2)      # Generate an array with random values
print(e)                     # Output: [[ 0.12345678  0.87654321]
                             #          [ 0.23456789  0.76543210]
                             #          [ 0.34567890  0.65432109]]

f = np.arange(20, 61)       # Generate values from 20 to 60
print(f)                     # Output: [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.80798773 0.73981315]
 [0.7489539  0.09111935]
 [0.9454451  0.77595714]]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]


In [35]:
# indexing and slicing arrays

import numpy as np

a = np.array([10, 20, 30, 40])

i = 2
j = 4
n = 2

print(a[i]) # Retrieve the element at index i, where i is an integer (index begins at 0).
# Output: 30
print(a[-i]) # Retrieve the element at index -i, where i is a positive integer (index begins at -1).
# Output: 30
print(a[i:j]) # Retrieve the elements from index i up to, but not including, index j, where i and j are integers.
# Output: [30 40]
print(a[:]) # Retrieve all elements of the array.
# Output: [10 20 30 40]
print(a[:i]) # Retrieve the elements from the beginning of the array up to, but not including, index i, where i is an integer.
# Output: [10 20]
print(a[j:]) # Retrieve the elements from index j to the end of the array, where j is an integer.
# Output: []
print(a[i:j:n]) # Retrieve the elements from index i up to, but not including, index j, with a step size of n, where i, j, and n are integers.
# Output: [30]
print(a[::-1]) # Retrieve all elements of the array in reverse order.
# Output: [40 30 20 10]

30
30
[30 40]
[10 20 30 40]
[10 20]
[]
[30]
[40 30 20 10]


In [36]:
# NumPy arrays support slicing.
# Since arrays may be multi-dimensional, you must specify a slice for each dimension of the array

# Filename: array_indexing_slicing_example.py

import numpy as np

# Create a rank 2 array with shape (3, 4)
# [[10  20  30  40]
#  [50  60  70  80]
#  [90 100 110 120]]
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
# Use slicing to extract a subarray containing the first 2 rows
# and columns 2 and 3; b will be the following array of shape (2, 2):
# [[30 40]
#  [70 80]]
b = a[:2, 2:4]
# A slice of an array is a view of the original data, so changing it
# will also change the original array.
print(a[0, 2])   # Output: 30
b[0, 0] = 99     # b[0, 0] refers to the same data as a[0, 2]
print(a[0, 2])   # Output: 99

30
99


In [37]:
# Example of array slicing

import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[:, 2:])
# Output:
# [[ 3  4]
#  [ 7  8]
#  [11 12]]

print(a[:2, :3])
# Output:
# [[1 2 3]
#  [5 6 7]]

print(a[:2, 1:])
# Output:
# [[2 3 4]
#  [6 7 8]]

[[ 3  4]
 [ 7  8]
 [11 12]]
[[1 2 3]
 [5 6 7]]
[[2 3 4]
 [6 7 8]]


In [38]:
# Filename: array_indexing_slicing_example2.py

import numpy as np

# Create a rank 2 array with shape (3, 4)
# [[ 11  12  13  14]
#  [ 15  16  17  18]
#  [ 19  20  21  22]]
a = np.array([[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]])

# Mixing integer indexing with slices yields an array of lower rank, 
# while using only slices yields an array of the same rank as the original:
row_r1 = a[2, :]    # Rank 1 view of the third row of a
row_r2 = a[2:3, :]  # Rank 2 view of the third row of a
print(row_r1, row_r1.shape)  # Output: [19 20 21 22] (4,)
print(row_r2, row_r2.shape)  # Output: [[19 20 21 22]] (1, 4)

# The same distinction applies when accessing columns of an array:
col_r1 = a[:, 2] # Combine integer indexing with slice indexing -> an array with lower rank, i.e. 1-D array
col_r2 = a[:, 2:3] 
print(col_r1, col_r1.shape)  # Output: [13 17 21] (3,)
print(col_r2, col_r2.shape)  # Output: [[13]
                             #          [17]
                             #          [21]] (3, 1)

[19 20 21 22] (4,)
[[19 20 21 22]] (1, 4)
[13 17 21] (3,)
[[13]
 [17]
 [21]] (3, 1)


In [39]:
# Filename: integer_array_indexing_example.py

import numpy as np

a = np.array([[7, 8], [9, 10], [11, 12]])

# An example of integer array indexing.
# The returned array will have shape (3,)
print(a[[0, 1, 2], [1, 0, 1]])  # Output: [ 8  9 12]

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 1], a[1, 0], a[2, 1]]))  # Output: [ 8  9 12]

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[1, 1], [0, 0]])  # Output: [9 9]

# Equivalent to the previous integer array indexing example
print(np.array([a[1, 0], a[1, 0]]))  # Output: [9 9]

[ 8  9 12]
[ 8  9 12]
[9 9]
[9 9]


In [40]:
# Integer array indexing enables to create arbitrary arrays using the data from another array.

# My example

import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

# Q1: we need to get an array of [2, 3, 6]
b = a[[0, 1, 2], [1, 0, 1]]

print(b)

# Q2: 1, 1, 3, 4, 3, 5
c = a[[0, 0, 1, 1, 1, 2], [0, 0, 0, 1, 0, 0]]

print(c)


[2 3 6]
[1 1 3 4 3 5]


In [41]:
# Filename: integer_array_indexing_example2.py

import numpy as np

# Create a new array from which we will select elements
a = np.array([[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]])

print(a)  # Output: [[13 14 15]
          #          [16 17 18]
          #          [19 20 21]
          #          [22 23 24]]

b = np.array([1, 0, 2, 1])  # Create an array of indices
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Output: [14 16 21 23]
# Modify one element from each row of a using the indices in b
a[np.arange(4), b] += 5

print(a)  # Output: [[13 19 15]
          #          [21 17 18]
          #          [19 20 26]
          #          [22 28 24]]

[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
[14 16 21 23]
[[13 19 15]
 [21 17 18]
 [19 20 26]
 [22 28 24]]


In [42]:
#  For reference to the above function

import numpy as np

print(np.arange(4))  # Output: [0 1 2 3]

[0 1 2 3]


In [43]:
# Filename: boolean_array_indexing_example.py

import numpy as np

a = np.array([[7, 8], [9, 10], [11, 12]])

bool_idx = (a < 10)   # Identify elements of a that are less than 10; this creates a numpy 
                      # array of Booleans with the same shape as a, where each entry in bool_idx 
                      # indicates whether the corresponding element of a is < 10.

print(bool_idx)      # Output: [[ True  True]
                      #         [ True False]
                      #         [False False]]

# Use boolean array indexing to create a rank 1 array of the elements of a 
# corresponding to the True values in bool_idx
print(a[bool_idx])  # Output: [7 8 9]

# All of the above can be done in one concise statement:
print(a[a < 10])    # Output: [7 8 9]

[[ True  True]
 [ True False]
 [False False]]
[7 8 9]
[7 8 9]


In [44]:
# Filename: dtype_example.py

import numpy as np

x = np.array([3, 4])   # Allow NumPy to infer the data type
print(x.dtype)         # Output: int64

x = np.array([3.5, 4.5])   # Allow NumPy to infer the data type
print(x.dtype)             # Output: float64

x = np.array([3, 4], dtype=np.float32)   # Specify a specific data type
print(x.dtype)                           # Output: float32

int64
float64
float32


In [45]:
# Data Types
import numpy as np

a = np.array([3, 4.5])

print(a)
print(a.dtype)

[3.  4.5]
float64


In [ ]:
# Data Types Reference

import numpy as np

np.int8   # 8-bit integer (-128 to 127)
np.int16  # 16-bit integer (-32,768 to 32,767)
np.int32  # 32-bit integer (-2,147,483,648 to 2,147,483,647)
np.int64  # 64-bit integer (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)
np.uint8  # 8-bit unsigned integer (0 to 255)
np.uint16 # 16-bit unsigned integer (0 to 65,535)
np.uint32 # 32-bit unsigned integer (0 to 4,294,967,295)
np.uint64 # 64-bit unsigned integer (0 to 18,446,744,073,709,551,615)
np.float16  # Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
np.float32  # Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
np.float64  # Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
np.float128 # Extended precision float (if available on the platform)
np.complex64   # Complex number, represented by two 32-bit floats (real and imaginary parts)
np.complex128  # Complex number, represented by two 64-bit floats (real and imaginary parts)
np.complex256  # Complex number, represented by two 128-bit floats (real and imaginary parts)
np.bool_    # Boolean type storing True and False values
np.object_  # Python object type
np.str_     # String type
np.byte    # Byte type (equivalent to np.int8)
np.datetime64  # Date and time type
np.timedelta64 # Difference between two date, time, or datetime values
np.void     # Raw data type (used for structured arrays)

In [47]:
# Filename: array_math_example.py

# Basic mathematical functions operate elementwise on arrays, 
# and are available both as operator overloads and as functions in the numpy module.

import numpy as np

x = np.array([[2, 3], [4, 5]], dtype=np.float64)
y = np.array([[6, 7], [8, 9]], dtype=np.float64)

# Elementwise sum; both yield the array
# [[ 8.0 10.0]
#  [12.0 14.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both yield the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both yield the array
# [[12.0 21.0]
#  [32.0 45.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both yield the array
# [[0.33333333 0.42857143]
#  [0.5        0.55555556]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; yields the array
# [[1.41421356 1.73205081]
#  [2.         2.23606798]]
print(np.sqrt(x))

[[ 8. 10.]
 [12. 14.]]
[[ 8. 10.]
 [12. 14.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[12. 21.]
 [32. 45.]]
[[12. 21.]
 [32. 45.]]
[[0.33333333 0.42857143]
 [0.5        0.55555556]]
[[0.33333333 0.42857143]
 [0.5        0.55555556]]
[[1.41421356 1.73205081]
 [2.         2.23606798]]


In [ ]:
# Vectors, Matrices and Tensors

# Vectors: 1-D arrays of numerical values
# Matrices: 2-D arrays of numerical values
# Tensors: arrays of three or more dimensions

In [48]:
# Filename: dot_product_example.py

import numpy as np

x = np.array([[2, 4], [6, 8]])
y = np.array([[1, 3], [5, 7]])
v = np.array([8, 9])
w = np.array([10, 11])

# Dot product of vectors; both yield 179
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both yield the rank 1 array [52 120]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both yield the rank 2 array
# [[22 34]
#  [46 74]]
print(x.dot(y))
print(np.dot(x, y))

179
179
[ 52 120]
[ 52 120]
[[22 34]
 [46 74]]
[[22 34]
 [46 74]]


In [49]:
# Filename: matrix_operations.py

import numpy as np

a = np.array([[2, 3], [5, 7]])
b = np.array([[4, 1], [6, 3]])
u = np.array([8, 9])
v = np.array([10, 11])

# Inner product of vectors; both yield 179
print(np.matmul(u, v))
print(u @ v)

# Matrix / vector product; both yield the rank 1 array [43 103]
print(np.matmul(a, u))
print(a @ u)

# Matrix / matrix product; both yield the rank 2 array
# [[26 11]
#  [62 26]]
print(np.matmul(a, b))
print(a @ b)

179
179
[ 43 103]
[ 43 103]
[[26 11]
 [62 26]]
[[26 11]
 [62 26]]


In [ ]:
# Filename: matrix_operations.py
# Same as dot product example

import numpy as np

a = np.array([[2, 4], [6, 8]])
b = np.array([[1, 3], [5, 7]])
u = np.array([8, 9])
v = np.array([10, 11])

# Inner product of vectors; both yield 170
print(np.matmul(u, v))
print(u @ v)

# Matrix / vector product; both yield the rank 1 array [52 120]
print(np.matmul(a, u))
print(a @ u)

# Matrix / matrix product; both yield the rank 2 array
# [[22 34]
#  [46 74]]
print(np.matmul(a, b))
print(a @ b)

179
179
[ 52 120]
[ 52 120]
[[22 34]
 [46 74]]
[[22 34]
 [46 74]]


In [50]:
# Filename: mean_func.py
 
import numpy as np

y = np.array([[5, 10], [15, 20]])

print(np.mean(y))          # Calculate the mean of all elements; output 12.5
print(np.mean(y, axis=0))  # Calculate the mean of each column; output [10. 15.]
print(np.mean(y, axis=1))  # Calculate the mean of each row; output [7.5 17.5]

12.5
[10. 15.]
[ 7.5 17.5]


In [51]:
# Matrix transposition

# Filename: transpose_example.py

import numpy as np

a = np.array([[5, 6], [7, 8]])
print(a)               # Output [[5 6]
                       #         [7 8]]
print(a.T)             # Output [[5 7]
                       #         [6 8]]
print(np.transpose(a)) # Output [[5 7]
                       #         [6 8]]
print(a.transpose())   # Output [[5 7]
                       #         [6 8]]

[[5 6]
 [7 8]]
[[5 7]
 [6 8]]
[[5 7]
 [6 8]]
[[5 7]
 [6 8]]


In [52]:
# Filename: transpose_example2.py

import numpy as np
# Create a 3D array
# (2 layers, 4 rows, and 3 columns)
# with numbers 0 to 23.
array = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8],
                   [ 9, 10, 11]],
                  [[12, 13, 14],
                   [15, 16, 17],
                   [18, 19, 20],
                   [21, 22, 23]]])

# The transpose function can rearrange the axes of the array.
# For instance, if we want to 
# move the current last axis (i.e., 2) 
# to the front (as axis 0),
# shift the current first axis (i.e., 0) 
# to the middle (as axis 1),
# and place the current second axis (i.e., 1) 
# at the end (as axis 2).
# We specify the order in transpose as [2, 0, 1].
print(np.transpose(array, [2, 0, 1])) 
# Equivalent output using the line below
print(array.transpose([2, 0, 1]))

# Output will be [[[ 0  3  6  9]                
#                  [12 15 18 21]]
#
#                 [[ 1  4  7 10]
#                  [13 16 19 22]]
#
#                 [[ 2  5  8 11]
#                  [14 17 20 23]]]

[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]
[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]


In [ ]:
# PS: I think it is the most difficult part of NumPy in this syllabus.

# Example for transpose with different order

import numpy as np

array = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8],
                   [ 9, 10, 11]],
                  [[12, 13, 14],
                   [15, 16, 17],
                   [18, 19, 20],
                   [21, 22, 23]]])

# 0: The big matrix
# 1: Rows
# 2: Columns

print(np.transpose(array, [0, 2, 1]))

print(array.transpose([1, 0, 2]))

print(array.transpose([1, 2, 0]))

print(array.transpose([2, 0, 1]))

print(array.transpose([2, 1, 0]))






[[[ 0  3  6  9]
  [ 1  4  7 10]
  [ 2  5  8 11]]

 [[12 15 18 21]
  [13 16 19 22]
  [14 17 20 23]]]
[[[ 0  1  2]
  [12 13 14]]

 [[ 3  4  5]
  [15 16 17]]

 [[ 6  7  8]
  [18 19 20]]

 [[ 9 10 11]
  [21 22 23]]]
[[[ 0 12]
  [ 1 13]
  [ 2 14]]

 [[ 3 15]
  [ 4 16]
  [ 5 17]]

 [[ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]]]
[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]
[[[ 0 12]
  [ 3 15]
  [ 6 18]
  [ 9 21]]

 [[ 1 13]
  [ 4 16]
  [ 7 19]
  [10 22]]

 [[ 2 14]
  [ 5 17]
  [ 8 20]
  [11 23]]]


In [ ]:
# Filename: transpose_example3.py

# It is important to note that transposing a one-dimensional array has no effect.

import numpy as np

vector = np.array([1, 2, 3])
print(vector)                # Output [1 2 3]
print(vector.T)              # Output [1 2 3]
print(np.transpose(vector))  # Output [1 2 3]

[1 2 3]
[1 2 3]
[1 2 3]


In [105]:
# Array reshaping, i.e. changing the shape of an array

# Syntax: np.reshape(<array>, <new_shape>)

# Filename: reshape_example.py

import numpy as np

array1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])
array2 = array1.reshape(4, 3)   # Reshape array1 into a 2D array with 4 rows and 3 columns
# array2 = array1.reshape(4, -1) # This line achieves the same result as array1.reshape(4, 3)
print(array2) # Output [[ 10  20  30]
               #         [ 40  50  60]
               #         [ 70  80  90]
               #         [100 110 120]]
print("Shape of array2:", array2.shape) # Output Shape of array2: (4, 3)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Shape of array2: (4, 3)


In [ ]:
# Powerpoint Question

import numpy as np

array = np.arange(24).reshape(2, 3, 4)

# 2 big matrix with 3 rows and 4 columns

print(array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# Expanding Array Dimensions

# i.e. arr = np.array([1, 2, 3, 4]) -> np.array([[1], [2], [3], [4]])
# From 1-D array to 2-D array

# Filename: newaxis_example.py

import numpy as np

array1 = np.array([10, 20, 30, 40, 50])
print(array1)  # Output: [10 20 30 40 50]

# Convert 1D array to a row vector using np.newaxis
# Important: np.newaxis is an alias for None
array2 = array1[np.newaxis]
print(array2)  # Output: [[10 20 30 40 50]]

# Convert 1D array to a row vector using None
array3 = array1[None]
print(array3)  # Output: [[10 20 30 40 50]]

array4 = np.array([[7, 8, 9], [10, 11, 12]])
print(array4)  # Output: [[ 7  8  9]
               #          [10 11 12]]

array5 = array4[np.newaxis]
print(array5)  # Output: [[[ 7  8  9]
               #           [10 11 12]]]

[10 20 30 40 50]
[[10 20 30 40 50]]
[[10 20 30 40 50]]
[[ 7  8  9]
 [10 11 12]]
[[[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Filename: newaxis_example2.py

import numpy as np

array1 = np.array([[7, 8, 9], [10, 11, 12]])
print(array1)  # Output: [[ 7  8  9]
               #          [10 11 12]]

# np.newaxis adds a new dimension of size 1, i.e., 1 column
array2 = array1[:, :, np.newaxis]  # Equivalent to array2 = array1[..., np.newaxis]

# 0: big matrix
# 1: rows
# 2: columns

print(array2)  # Output: [[[ 7] 
               #           [ 8] 
               #           [ 9]]
               #          [[10]
               #           [11]
               #           [12]]]

print(array2.shape) # Output: (2, 3, 1), indicating 2 layers, 3 rows, and 1 column

[[ 7  8  9]
 [10 11 12]]
[[[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
(2, 3, 1)


In [113]:
# Filename: newaxis_example3.py

import numpy as np

array1 = np.array([[5, 6, 7], [8, 9, 10]])
print(array1)  # Output: [[ 5  6  7]
               #          [ 8  9 10]]

# np.newaxis adds a new dimension of size 1, i.e., 1 row
# highest dimension, i.e., row
array2 = array1[np.newaxis, :, :]

print(array2)  # Output: [[[ 5  6  7]
               #           [ 8  9 10]]]

print(array2.shape) # Output: (1, 2, 3), indicating 1 layer, 2 rows, and 3 columns

[[ 5  6  7]
 [ 8  9 10]]
[[[ 5  6  7]
  [ 8  9 10]]]
(1, 2, 3)


In [115]:
# Filename: expand_dims_example.py
 
import numpy as np

array1 = np.array([[7, 8, 9], [10, 11, 12]])
print(array1)  # Output: [[ 7  8  9]
               #          [10 11 12]]

# 1 means adding a new dimension of size 1, after the 1st dimension
array2 = np.expand_dims(array1, axis=1)

print(array2)  # Output: [[[ 7  8  9]]
               #          [[10 11 12]]]

print(array2.shape) # Output: (2, 1, 3), indicating 2 layers, 1 row, and 3 columns

[[ 7  8  9]
 [10 11 12]]
[[[ 7  8  9]]

 [[10 11 12]]]
(2, 1, 3)


In [117]:
# Filename: expand_dims_example2.py
   
import numpy as np

array1 = np.array([[13, 14, 15], [16, 17, 18]])
print(array1)  # Output: [[13 14 15]
               #          [16 17 18]]

# 2 means adding a new dimension of size 1, after the 2nd dimension
array2 = np.expand_dims(array1, axis=2)

print(array2)  # Output: [[[13]
               #           [14]
               #           [15]]
               #          [[16]
               #           [17]
               #           [18]]]

print(array2.shape) # Output: (2, 3, 1), indicating 2 layers, 3 rows, and 1 column

[[13 14 15]
 [16 17 18]]
[[[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]]
(2, 3, 1)


In [ ]:
# View and Copy are already known so ignore this part.

In [ ]:
import numpy as np

# variables
arr = np.array([1, 2, 3])
new_shape = (3, 1)
n = 1

# Operations that produce a view
arr[1:3]
arr.reshape(new_shape)
arr.transpose() # or arr.T, np.transpose(arr)
arr.flatten()
arr[:]
arr.view()
arr[np.newaxis]
np.expand_dims(arr, axis=0)

# Operations that produce a copy
np.copy(arr)
arr.copy()
arr.astype(np.float64) # Converts to float64 and returns a copy
np.array(arr) # Creates a new array (copy) from an exist one
arr.tolist() # Converts to a Python list and returns a copy
arr[np.arange(n)] # Integer array indexing always returns a copy


In [ ]:
# Broadcasting

# When having a smaller array and a larger array, 
# NumPy can automatically expand the smaller array to match the shape of the larger array during arithmetic operations. 
# This is known as broadcasting.

import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
add = np.array([1, 1, 4])
y = x + add  # Broadcasting happens here
print(y)  # Output: [[ 2  3  7]
          #          [ 5  6 10]
          #          [ 8  9 13]
          #          [11 12 16]]

[[ 2  3  7]
 [ 5  6 10]
 [ 8  9 13]
 [11 12 16]]


In [ ]:
# Filename: broadcasting_example.py

# The mechanism of broadcasting is used to perform operations between arrays of different shapes.
        
import numpy as np

# We will add the vector v to each row of the matrix x, storing the result in y
x = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10], [11, 12, 13]])
v = np.array([2, 1, 2])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x using an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)  # Output: [[ 4  4  6] 
          #          [ 7  7  9]
          #          [10 10 12]
          #          [13 13 15]]

[[ 4  4  6]
 [ 7  7  9]
 [10 10 12]
 [13 13 15]]


In [123]:
# Filename: broadcasting_example2.py

# Actually, example 1 and example 2 are the same.
    
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10], [11, 12, 13]])
v = np.array([2, 1, 2])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Output: [[2 1 2]
                          #          [2 1 2]
                          #          [2 1 2]
                          #          [2 1 2]]
y = x + vv                # Add x and vv elementwise

print(y)                  # Output: [[ 4  4  6] 
                          #          [ 7  7  9]
                          #          [10 10 12]
                          #          [13 13 15]]

[[2 1 2]
 [2 1 2]
 [2 1 2]
 [2 1 2]]
[[ 4  4  6]
 [ 7  7  9]
 [10 10 12]
 [13 13 15]]


In [124]:
# Filename: broadcasting_demo.py

import numpy as np

# We will add the vector v to every row of the matrix x,
# and store the results in the matrix y
x = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10], [11, 12, 13]])
v = np.array([2, 1, 2])
y = x + v  # Add v to each row of x using broadcasting
print(y)   # Print [[ 4  4  6]
           #        [ 7  7  9]
           #        [10 10 12]
           #        [13 13 15]]

[[ 4  4  6]
 [ 7  7  9]
 [10 10 12]
 [13 13 15]]


In [ ]:
# Filename: broadcasting_rule1.py
  
import numpy as np

# A = np.array([1, 2, 3]) # shape (3,)
# B = np.array([2]) # shape (1,)
# Do they share the same rank? -> Rank 1 and Rank 1 -> Yes
# Are they compatible in all dimensions? -> Since B has a size of 1 in that dimension -> Yes
# Thus, they are compatible.

A = np.array([1, 2, 3])
print(A.ndim)     # Print 1
print(A.shape)    # Print (3,)
B = np.array([2])
print(B.ndim)     # Print 1
print(B.shape)    # Print (1,)
print(A * B)      # Print [2, 4, 6]

1
(3,)
1
(1,)
[2 4 6]


In [ ]:
# Filename: broadcasting_rule2.py
         
import numpy as np

# A = np.array([1, 2, 3]) # shape (3,)
# B = np.array([[4, 4, 4], [3, 3, 3]]) # shape (2, 3)
# Do they share the same rank? -> Rank 1 and Rank 2 -> No
# DO they share the same rightmost dimensions? -> Both of A and B are 3 -> Yes
# Yes -> Add leading 1s to the shape of A -> (1, 3)
# Are they compatible in all dimensions? -> Yes, since A has a size of 1 in that dimension
# Thus, they are compatible.


A = np.array([1, 2, 3])
print(A.ndim)  # Print 1
print(A.shape) # Print (3,)
B = np.array([[4, 4, 4], [3, 3, 3]])
print(B.ndim)  # Print 2
print(B.shape) # Print (2, 3)
print(A * B)   # Print [[ 4  8 12]
               #        [ 3  6  9]]

1
(3,)
2
(2, 3)
[[ 4  8 12]
 [ 3  6  9]]


In [ ]:
# Testing for broadcasting examples with different shapes

import numpy as np

# a = np.arange(225).reshape(15, 3, 5) # shape (15, 3, 5)
# b = np.arange(45).reshape(15, 3)     # shape (15, 3)
# Do they share the same rank? -> Rank 3 and Rank 2 -> No
# No -> Do they share the same rightmost dimensions? -> A is 5 but B is 3 -> No
# Thus, they are not compatible.

a = np.arange(225).reshape(15, 3, 5)
b = np.arange(45).reshape(15, 3)

print(a * b)

"""
ValueError                                Traceback (most recent call last)
Cell In[136], line 15
     12 a = np.arange(225).reshape(15, 3, 5)
     13 b = np.arange(45).reshape(15, 3)
---> 15 print(a * b)

ValueError: operands could not be broadcast together with shapes (15,3,5) (15,3) 
"""

In [ ]:
# Broadcasting in action

# Filename: centering_a_dataset.py

import numpy as np
scores = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
score_mean = scores.mean(0)  # 0 indicates the first dimension, i.e. columns
print(score_mean)            # Print array([7., 8., 9.])

scores_centered = scores - score_mean
print(scores_centered)    # Print array([[-6., -6., -6.],
                          #              [-3., -3., -3.],
                          #              [ 0.,  0.,  0.],
                          #              [ 3.,  3.,  3.],
                          #              [ 6.,  6.,  6.]])
print(scores_centered.mean(axis=0))    # Print array([0., 0., 0.])

[7. 8. 9.]
[[-6. -6. -6.]
 [-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]
 [ 6.  6.  6.]]
[0. 0. 0.]


In [ ]:
# Why NumPy Arrays are Better?

# NumPy arrays consume less memory than Python lists.
# NumPy arrays are faster than Python lists for numerical operations.
# NumPy arrays are more convenient and provide more functionality for numerical computations than Python lists.

In [ ]:
# A NumPy arrays contains a single data type, while a Python list can contain elements of different data types.
# A Python list contains a reference to a block of references, each of which references to a full Python object.

In [ ]:
# Filename: memory_consumption.py

import numpy as np, sys, gc  # Import numpy package, system, and gc module

def actualsize(input_object):
    memory_size = 0                # memory_size: the actual memory size of "input_object"
                                   # Initialize it to 0
    ids = set()                    # ids: An empty set to store all the ids of objects in "input_object"
    objects = [input_object]       # objects: A list with "input_object" (traverse from "input_object")
    while objects:                 # While "objects" is non-empty
        new = []                   # new: An empty list to keep the items linked by "objects"
        for obj in objects:        # obj: Each object in "objects"
            if id(obj) not in ids: # If the id of "obj" is not in "ids"
               ids.add(id(obj))    # Add the id of the "obj" to "ids"
               memory_size += sys.getsizeof(obj) # Use getsizeof to determine the size of "obj"
                                   # and add it to "memory_size"
               new.append(obj)     # Add "obj" to "new"
        objects = gc.get_referents(*new)  # Update "objects" with the list of objects directly
                                          # referred to by *new
    return memory_size             # Return "memory_size"

L = list(range(0, 1000))           # Define a Python list of 1000 elements
A = np.arange(1000)                # Define a NumPy array of 1000 elements
# Print size of the whole list, it prints "Size of the whole list in bytes: 36056"
print("Size of the whole list in bytes:", actualsize(L))
# Print size of the whole NumPy array, it prints "Size of the whole NumPy array in bytes: 8112"
print("Size of the whole NumPy array in bytes:", actualsize(A))

Size of the whole list in bytes: 36056
Size of the whole NumPy array in bytes: 8112


In [153]:
# Filename: time_comparison.py

# TODO: Try to use decorator instead of just writing the code directly.

import numpy as np       # Import required packages
import time as t

size = 1000000           # Size of arrays and lists

list1 = range(size)      # Declare lists
list2 = range(size)
array1 = np.arange(size) # Declare arrays
array2 = np.arange(size)

# Capture time before the multiplication of Python lists
initialTime = t.time()
# Multiply elements of both lists and store in another list
resultList = [(a * b) for a, b in zip(list1, list2)]
# Calculate execution time, it prints "Time taken by Lists: 0.13024258613586426 s"
print("Time taken by Lists:", (t.time() - initialTime), "s")

# Capture time before the multiplication of NumPy arrays
initialTime = t.time()
# Multiply elements of both NumPy arrays and store in another NumPy array
resultArray = array1 * array2
# Calculate execution time, it prints "Time taken by NumPy Arrays: 0.006006956100463867 s"
print("Time taken by NumPy Arrays:", (t.time() - initialTime), "s")

Time taken by Lists: 0.06737136840820312 s
Time taken by NumPy Arrays: 0.0036592483520507812 s


In [154]:
# Filename: effect_of_operations.py

import numpy as np # Import NumPy package

ls = [1, 2, 3]      # Declare a list
arr = np.array(ls)  # Convert the list into a NumPy array

try:
    ls = ls + 4    # Add 4 to each element of the list
except TypeError:
    print("Lists don't support list + int")

# Now on the array
try:
    arr = arr + 4  # Add 4 to each element of the NumPy array
    print("Modified NumPy array: ", arr)  # Print the NumPy array
except TypeError:
    print("NumPy arrays don't support array + int")

# Note: In COMP1023, try-except is not covered.
# But why don't cover this???? It is very important so you must know it.

Lists don't support list + int
Modified NumPy array:  [5 6 7]


In [155]:
# Key Terms and Acknowledgments

# Array indexing and slicing
# Boolean array indexing
# Broadcasting
# Dot product
# expand_dims
# Integer array indexing
# Matrix
# Matrix multiplication
# newaxis
# NumPy array
# Rank
# Reshaping
# Shape
# Sum function
# Tensor
# Transpose
# Vector


In [156]:
# Other built-in functions
# Answer to some practice problems on PowerPoint
# Review the concepts

# Summary

import numpy as np

# Array generations
# Create arrays of different shapes and values (e.g., zeros, ones, full, eye, random)
# a = np.zeros((3,3))
# a = np.ones((2,3))
# a = np.full((3,2), 5)
# a = np.eye(3)
# a = np.random.rand(3,2)

# Find the indices of non-zero elements in the array
a = np.array([0, 3, 0, 0, 4, 0])
print(a.nonzero())


# Filter the array to include only non-zero elements
print(a[a != 0])

# Compute various statistics of the array (i.e. max, min, mean, std, median)
a = np.array([1, 13, 0, 56, 71, 22])
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))

# Create a 4x4 array with values ranging from 0 to 15
a = np.arange(0, 16).reshape(4, 4)
# print(a)

# Transpose the array in different ways
# print(a.T)
# print(np.transpose(a))
# print(a.transpose())

# Append values to the end of an array
a = np.array([1, 2, 3])
print(np.append(arr=a, values=[4, 5, 6]))

# Perform element-wise arithmetic operations (addition, subtraction, multiplication, division) on two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

# Calculate the sum of all elements in an array
print(np.sum(a))

# Calculate the natural logarithm of each element in an array
print(np.log(a))

# Create a 1-D array of size 5 filled with the value 8
a = np.full((5, ), 8)
print(a)

# Sort an array and find the indices of the maximum and minimum values
a = np.array([2, 5, 7, 3, 6])
print(np.sort(a)) # Sorted array
print(np.argmax(a))
print(np.argmin(a)) # Indices of max and min values
print(np.argsort(a)) # Indices that would sort the array

# Perform matrix operations (e.g., inverse, determinant) on a 3x3 matrix
a = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(np.linalg.inv(a)) # Inverse of a matrix
print(np.linalg.det(a)) # Determinant of a matrix

# Calculate the absolute value of each element in an array
print(np.abs(a)) # Absolute values of each element

# Extract a specific column from a 2-D array
a = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
b = a[:, 2]
print(b)

# Extract the sub-array consisiting of the odd rows and even columns from a 5x4 array.
a = np.array([[3, 6, 9, 12], [15, 18, 21, 24], [27, 30, 33, 36], [39, 42, 45, 48], [51, 54, 57, 60]])
print(a[::2, 1::2])

# Extract the sub-array consisiting of the even rows and odd columns from a 5x4 array.
print(a[1::2, ::2])


(array([1, 4]),)
[3 4]
71
0
27.166666666666668
27.088845592892206
17.5
[1 2 3 4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
6
[0.         0.69314718 1.09861229]
[8 8 8 8 8]
[2 3 5 6 7]
2
0
[0 3 1 4 2]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
-306.0
[[6 1 1]
 [4 2 5]
 [2 8 7]]
[33 66 99]
[[ 6 12]
 [30 36]
 [54 60]]
[[15 21]
 [39 45]]
