- NumPy stands for Numerical Python and serves as the fundamental library for numerical and scientific calculations in the Python programming language.
- It offers a high-efficiency multidimensional array structure along with various tools for manipulating these arrays.

In [6]:
import numpy as np

a = np.array([[114, 514], [1919, 810]])
print(type(a))
print(a)
print(a.shape)
print(a[0, 1], a[1, 0])
print(np.linalg.inv(a))



<class 'numpy.ndarray'>
[[ 114  514]
 [1919  810]]
(2, 2)
514 1919
[[-0.00090601  0.00057493]
 [ 0.00214647 -0.00012751]]


- A NumPy array represents a grid of values that are all of the same data type and are indexed by a tuple of non-negative integers.
- The number of dimensions in the array is referred to as the rank.
- The shape of an array is defined as a tuple of integers that specifies the size of the array in each dimension.
- We can create NumPy arrays from nested lists in Python and retrieve elements using
square brackets.


In [7]:
# Filename: array_generation.py
import numpy as np
a = np.zeros((3,3)) # Generate an array filled with zeros
print(a) 
# Output: 
# [[ 0. 0. 0.]
# [ 0. 0. 0.]
# [ 0. 0. 0.]]
b = np.ones((2,3)) # Generate an array filled with ones
print(b) 
# Output: 
# [[ 1. 1. 1.]
# [ 1. 1. 1.]]
c = np.full((3,2), 5) # Generate an array with a constant value
print(c) 
# Output: 
# [[ 5 5]
# [ 5 5]
# [ 5 5]]
d = np.eye(3) # Generate a 3x3 identity matrix
print(d) 
# Output: 
# [[ 1. 0. 0.]
# [ 0. 1. 0.]
# [ 0. 0. 1.]]
e = np.random.rand(3,2) # Generate an array with random values
print(e) 
# Output: 
# [[ 0.12345678 0.87654321]
# [ 0.23456789 0.76543210]
# [ 0.34567890 0.65432109]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.96641497 0.04581583]
 [0.15885446 0.97673947]
 [0.85440888 0.82036291]]


- NumPy offers a variety of functions to create arrays.