- NumPy stands for Numerical Python and serves as the fundamental library for numerical and scientific calculations in the Python programming language.
- It offers a high-efficiency multidimensional array structure along with various tools for manipulating these arrays.

In [6]:
import numpy as np

a = np.array([[114, 514], [1919, 810]])
print(type(a))
print(a)
print(a.shape)
print(a[0, 1], a[1, 0])
print(np.linalg.inv(a))



<class 'numpy.ndarray'>
[[ 114  514]
 [1919  810]]
(2, 2)
514 1919
[[-0.00090601  0.00057493]
 [ 0.00214647 -0.00012751]]


- A NumPy array represents a grid of values that are all of the same data type and are indexed by a tuple of non-negative integers.
- The number of dimensions in the array is referred to as the rank.
- The shape of an array is defined as a tuple of integers that specifies the size of the array in each dimension.
- We can create NumPy arrays from nested lists in Python and retrieve elements using
square brackets.


In [7]:
# Filename: array_generation.py
import numpy as np
a = np.zeros((3,3)) # Generate an array filled with zeros
print(a) 
# Output: 
# [[ 0. 0. 0.]
# [ 0. 0. 0.]
# [ 0. 0. 0.]]
b = np.ones((2,3)) # Generate an array filled with ones
print(b) 
# Output: 
# [[ 1. 1. 1.]
# [ 1. 1. 1.]]
c = np.full((3,2), 5) # Generate an array with a constant value
print(c) 
# Output: 
# [[ 5 5]
# [ 5 5]
# [ 5 5]]
d = np.eye(3) # Generate a 3x3 identity matrix
print(d) 
# Output: 
# [[ 1. 0. 0.]
# [ 0. 1. 0.]
# [ 0. 0. 1.]]
e = np.random.rand(3,2) # Generate an array with random values
print(e) 
# Output: 
# [[ 0.12345678 0.87654321]
# [ 0.23456789 0.76543210]
# [ 0.34567890 0.65432109]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.96641497 0.04581583]
 [0.15885446 0.97673947]
 [0.85440888 0.82036291]]


- NumPy offers a variety of functions to create arrays.

In [8]:
# Slicing Numpy Arrays
import numpy as np
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
print(a[0:2, 1:4]) # Slicing rows 0-1 and columns 1-3
# Output:  [[2 3 4]
#           [7 8 9]]
print(a[:, 2])    # All rows, column 2
# Output:  [ 3  8 13]
print(a[1, :])    # Row 1, all columns
# Output:  [ 6  7  8  9 10]
print(a[-1, -2:]) # Last row, last two columns
# Output:  [14 15]
# NumPy offers a variety of functions to create arrays.

[[2 3 4]
 [7 8 9]]
[ 3  8 13]
[ 6  7  8  9 10]
[14 15]


In [9]:
# Exercise

a = np.array([[1,3,7,4,5],
              [6,2,8,9,10],
              [11,13,12,14,15]])
print(a[0:2,1:3]) # (a)
print(a[:, 2]) # (b)
print(a[1, :])  # (c)
print(a[-1, -2:]) # (d)

[[3 7]
 [2 8]]
[ 7  8 12]
[ 6  2  8  9 10]
[14 15]


![alt text](capture/image.png)

In [10]:
# Filename: array_indexing_slicing_example.py

import numpy as np

# Create a rank 2 array with shape (3, 4)
# [[10  20  30  40]
#  [50  60  70  80]
#  [90 100 110 120]]
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
# Use slicing to extract a subarray containing the first 2 rows
# and columns 2 and 3; b will be the following array of shape (2, 2):
# [[30 40]
#  [70 80]]
b = a[:2, 2:4]
# A slice of an array is a view of the original data, so changing it
# will also change the original array.
print(a[0, 2])   # Output: 30
b[0, 0] = 99     # b[0, 0] refers to the same data as a[0, 2]
print(a[0, 2])   # Output: 99

30
99


In [11]:
# Filename: array_indexing_slicing_example2.py

import numpy as np

# Create a rank 2 array with shape (3, 4)
# [[ 11  12  13  14]
#  [ 15  16  17  18]
#  [ 19  20  21  22]]
a = np.array([[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]])

# Mixing integer indexing with slices yields an array of lower rank, 
# while using only slices yields an array of the same rank as the original:
row_r1 = a[2, :]    # Rank 1 view of the third row of a
row_r2 = a[2:3, :]  # Rank 2 view of the third row of a
print(row_r1, row_r1.shape)  # Output: [19 20 21 22] (4,)
print(row_r2, row_r2.shape)  # Output: [[19 20 21 22]] (1, 4)

# The same distinction applies when accessing columns of an array:
col_r1 = a[:, 2]
col_r2 = a[:, 2:3]
print(col_r1, col_r1.shape)  # Output: [13 17 21] (3,)
print(col_r2, col_r2.shape)  # Output: [[13]
                             #          [17]
                             #          [21]] (3, 1)

[19 20 21 22] (4,)
[[19 20 21 22]] (1, 4)
[13 17 21] (3,)
[[13]
 [17]
 [21]] (3, 1)


In [12]:
# Filename: integer_array_indexing_example.py

import numpy as np

a = np.array([[7, 8], [9, 10], [11, 12]])

# An example of integer array indexing.
# The returned array will have shape (3,)
print(a[[0, 1, 2], [1, 0, 1]])  # Output: [ 8  9 12]

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 1], a[1, 0], a[2, 1]]))  # Output: [ 8  9 12]

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[1, 1], [0, 0]])  # Output: [9 9]

# Equivalent to the previous integer array indexing example
print(np.array([a[1, 0], a[1, 0]]))  # Output: [9 9]

[ 8  9 12]
[ 8  9 12]
[9 9]
[9 9]


In [13]:
# Filename: integer_array_indexing_example2.py

import numpy as np

# Create a new array from which we will select elements
a = np.array([[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]])

print(a)  # Output: [[13 14 15]
          #          [16 17 18]
          #          [19 20 21]
          #          [22 23 24]]

b = np.array([1, 0, 2, 1])  # Create an array of indices
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Output: [14 16 21 23]
# Modify one element from each row of a using the indices in b
a[np.arange(4), b] += 5

print(a)  # Output: [[13 19 15]
          #          [21 17 18]
          #          [19 20 26]
          #          [22 28 24]]

[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
[14 16 21 23]
[[13 19 15]
 [21 17 18]
 [19 20 26]
 [22 28 24]]
